package com.healthaxis.enums;

public enum NotificationType {
    APPOINTMENT_REMINDER, APPOINTMENT_CONFIRMED, APPOINTMENT_CANCELLED,
    EMERGENCY_ALERT, EMERGENCY_ASSIGNED,
    DISCHARGE_NOTICE, PAYMENT_CONFIRMATION, PAYMENT_DUE,
    BED_ASSIGNED, TRANSFER_NOTICE, GENERAL
}
